apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: null
  description: Python "3.11" microservice created via the DCP Golden Path
  tags:
    - python
    - microservice
  annotations:
    github.com/project-slug: hingerabhinav/null
spec:
  type: service
  lifecycle: experimental
  owner: null
